export const HTTP_CODE = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  UNAUTHORIZED: 401,
  INTERNAL_SERVER: 500,
  CONFLICT: 409,
};

export const ERROR_CODE = {
  INTERNAL_SERVER: 'INTERNAL_ERROR',
  DUPLICATE_KEY: 'DUPLICATE_KEY_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  BAD_REQUEST: 'BAD_REQUEST',
};

export const ERROR_MESSAGE = {
  SERVER: {
    INTERNAL_SERVER: 'Internal Server Error',
  },
  MONGO: {
    DUPLICATE_KEY: 'DUPLICATE_KEY_ERROR',
  },
};
