export const carSeed = [
  {
    brand: 'Toyota',
    model: 'Avanza 1.3 E',
    year: 2018,
    price: 145000000,
    mileage: 85000,
    engine_capacity: 1329,
    seat_capacity: 7,
    transmission: 'manual',
    fuel_type: 'gasoline',
    color: 'Silver',
    plate_region: 'Riau',
    image_url: 'https://example.com/avanza.jpg',
    description: 'MPV irit dan cocok untuk keluarga.',
    is_active: true,
  },
  {
    brand: 'Honda',
    model: 'Brio Satya E',
    year: 2019,
    price: 135000000,
    mileage: 60000,
    engine_capacity: 1198,
    seat_capacity: 5,
    transmission: 'manual',
    fuel_type: 'gasoline',
    color: 'Red',
    plate_region: 'Riau',
    image_url: 'https://example.com/brio.jpg',
    description: 'Hatchback kecil yang irit bahan bakar.',
    is_active: true,
  },
  {
    brand: 'Daihatsu',
    model: 'Xenia 1.3 R',
    year: 2017,
    price: 125000000,
    mileage: 90000,
    engine_capacity: 1329,
    seat_capacity: 7,
    transmission: 'manual',
    fuel_type: 'gasoline',
    color: 'White',
    plate_region: 'Riau',
    image_url: 'https://example.com/xenia.jpg',
    description: 'MPV keluarga dengan perawatan murah.',
    is_active: true,
  },
  {
    brand: 'Suzuki',
    model: 'Ertiga GL',
    year: 2020,
    price: 175000000,
    mileage: 50000,
    engine_capacity: 1462,
    seat_capacity: 7,
    transmission: 'automatic',
    fuel_type: 'gasoline',
    color: 'Grey',
    plate_region: 'Riau',
    image_url: 'https://example.com/ertiga.jpg',
    description: 'MPV nyaman dengan fitur modern.',
    is_active: true,
  },
  {
    brand: 'Toyota',
    model: 'Calya G',
    year: 2021,
    price: 150000000,
    mileage: 30000,
    engine_capacity: 1197,
    seat_capacity: 7,
    transmission: 'manual',
    fuel_type: 'gasoline',
    color: 'Black',
    plate_region: 'Riau',
    image_url: 'https://example.com/calya.jpg',
    description: 'LMPV hemat dan cocok untuk keluarga muda.',
    is_active: true,
  },
  {
    brand: 'Honda',
    model: 'Mobilio RS',
    year: 2018,
    price: 165000000,
    mileage: 70000,
    engine_capacity: 1496,
    seat_capacity: 7,
    transmission: 'manual',
    fuel_type: 'gasoline',
    color: 'Silver',
    plate_region: 'Riau',
    image_url: 'https://example.com/mobilio.jpg',
    description: 'MPV sporty dengan kabin luas.',
    is_active: true,
  },
  {
    brand: 'Mitsubishi',
    model: 'Xpander Ultimate',
    year: 2020,
    price: 220000000,
    mileage: 45000,
    engine_capacity: 1499,
    seat_capacity: 7,
    transmission: 'automatic',
    fuel_type: 'gasoline',
    color: 'White',
    plate_region: 'Riau',
    image_url: 'https://example.com/xpander.jpg',
    description: 'MPV modern dengan kenyamanan tinggi.',
    is_active: true,
  },
  {
    brand: 'Toyota',
    model: 'Innova Reborn G',
    year: 2019,
    price: 310000000,
    mileage: 80000,
    engine_capacity: 2393,
    seat_capacity: 7,
    transmission: 'manual',
    fuel_type: 'diesel',
    color: 'Black',
    plate_region: 'Riau',
    image_url: 'https://example.com/innova.jpg',
    description: 'MPV premium dan tangguh untuk perjalanan jauh.',
    is_active: true,
  },
  {
    brand: 'Suzuki',
    model: 'APV Arena',
    year: 2016,
    price: 110000000,
    mileage: 100000,
    engine_capacity: 1493,
    seat_capacity: 8,
    transmission: 'manual',
    fuel_type: 'gasoline',
    color: 'Silver',
    plate_region: 'Riau',
    image_url: 'https://example.com/apv.jpg',
    description: 'MPV serbaguna untuk keluarga besar.',
    is_active: true,
  },
  {
    brand: 'Daihatsu',
    model: 'Sigra R',
    year: 2022,
    price: 155000000,
    mileage: 25000,
    engine_capacity: 1197,
    seat_capacity: 7,
    transmission: 'manual',
    fuel_type: 'gasoline',
    color: 'Blue',
    plate_region: 'Riau',
    image_url: 'https://example.com/sigra.jpg',
    description: 'Mobil LCGC hemat bahan bakar.',
    is_active: true,
  },
  {
    brand: 'Toyota',
    model: 'Agya G',
    year: 2020,
    price: 135000000,
    mileage: 40000,
    engine_capacity: 1197,
    seat_capacity: 5,
    transmission: 'automatic',
    fuel_type: 'gasoline',
    color: 'Yellow',
    plate_region: 'Riau',
    image_url: 'https://example.com/agya.jpg',
    description: 'City car kecil dan lincah.',
    is_active: true,
  },
  {
    brand: 'Honda',
    model: 'Jazz RS',
    year: 2017,
    price: 180000000,
    mileage: 75000,
    engine_capacity: 1497,
    seat_capacity: 5,
    transmission: 'automatic',
    fuel_type: 'gasoline',
    color: 'Red',
    plate_region: 'Riau',
    image_url: 'https://example.com/jazz.jpg',
    description: 'Hatchback sporty dan stylish.',
    is_active: true,
  },
  {
    brand: 'Nissan',
    model: 'Grand Livina XV',
    year: 2016,
    price: 120000000,
    mileage: 95000,
    engine_capacity: 1498,
    seat_capacity: 7,
    transmission: 'manual',
    fuel_type: 'gasoline',
    color: 'Grey',
    plate_region: 'Riau',
    image_url: 'https://example.com/livina.jpg',
    description: 'MPV nyaman untuk perjalanan keluarga.',
    is_active: true,
  },
  {
    brand: 'Toyota',
    model: 'Rush TRD Sportivo',
    year: 2021,
    price: 245000000,
    mileage: 35000,
    engine_capacity: 1496,
    seat_capacity: 7,
    transmission: 'automatic',
    fuel_type: 'gasoline',
    color: 'White',
    plate_region: 'Riau',
    image_url: 'https://example.com/rush.jpg',
    description: 'SUV kompak dengan tampilan gagah.',
    is_active: true,
  },
  {
    brand: 'Daihatsu',
    model: 'Terios R',
    year: 2020,
    price: 230000000,
    mileage: 55000,
    engine_capacity: 1496,
    seat_capacity: 7,
    transmission: 'manual',
    fuel_type: 'gasoline',
    color: 'Black',
    plate_region: 'Riau',
    image_url: 'https://example.com/terios.jpg',
    description: 'SUV tangguh untuk segala medan.',
    is_active: true,
  },
  {
    brand: 'Suzuki',
    model: 'Ignis GX',
    year: 2019,
    price: 140000000,
    mileage: 60000,
    engine_capacity: 1197,
    seat_capacity: 5,
    transmission: 'manual',
    fuel_type: 'gasoline',
    color: 'Orange',
    plate_region: 'Riau',
    image_url: 'https://example.com/ignis.jpg',
    description: 'City car unik dengan desain compact SUV.',
    is_active: true,
  },
  {
    brand: 'Toyota',
    model: 'Yaris TRD',
    year: 2018,
    price: 190000000,
    mileage: 70000,
    engine_capacity: 1496,
    seat_capacity: 5,
    transmission: 'automatic',
    fuel_type: 'gasoline',
    color: 'Red',
    plate_region: 'Riau',
    image_url: 'https://example.com/yaris.jpg',
    description: 'Hatchback sporty dan responsif.',
    is_active: true,
  },
  {
    brand: 'Honda',
    model: 'HR-V E',
    year: 2020,
    price: 320000000,
    mileage: 50000,
    engine_capacity: 1498,
    seat_capacity: 5,
    transmission: 'automatic',
    fuel_type: 'gasoline',
    color: 'White',
    plate_region: 'Riau',
    image_url: 'https://example.com/hrv.jpg',
    description: 'SUV compact premium.',
    is_active: true,
  },
  {
    brand: 'Mitsubishi',
    model: 'Pajero Sport Dakar',
    year: 2019,
    price: 480000000,
    mileage: 85000,
    engine_capacity: 2442,
    seat_capacity: 7,
    transmission: 'automatic',
    fuel_type: 'diesel',
    color: 'Black',
    plate_region: 'Riau',
    image_url: 'https://example.com/pajero.jpg',
    description: 'SUV premium untuk medan berat.',
    is_active: true,
  },
  {
    brand: 'Toyota',
    model: 'Fortuner VRZ',
    year: 2021,
    price: 520000000,
    mileage: 40000,
    engine_capacity: 2393,
    seat_capacity: 7,
    transmission: 'automatic',
    fuel_type: 'diesel',
    color: 'Grey',
    plate_region: 'Riau',
    image_url: 'https://example.com/fortuner.jpg',
    description: 'SUV gagah dan berkelas.',
    is_active: true,
  },
];
